const ROLES = {
    AUTHOR: 'AUTHOR',
    SOLVER: 'SOLVER'
};
const TASK_STATUS = {
    PENDING: 'PENDING',
    STARTED: 'STARTED',
    COMPLETED: 'COMPLETED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED'
};

const STATUS_TRANSITIONS = {
    [TASK_STATUS.PENDING]: [TASK_STATUS.STARTED],
    [TASK_STATUS.STARTED]: [TASK_STATUS.COMPLETED],
    [TASK_STATUS.COMPLETED]: [TASK_STATUS.APPROVED, TASK_STATUS.REJECTED],
    [TASK_STATUS.APPROVED]: [],
    [TASK_STATUS.REJECTED]: [TASK_STATUS.STARTED]
};

const isValidTransition = (from, to) => {
    return (STATUS_TRANSITIONS[from] || []).includes(to);
};

const NOTIFICATION_TYPES = {
    TASK_ASSIGNED: 'TASK_ASSIGNED',
    TASK_APPROVED: 'TASK_APPROVED',
    TASK_REJECTED: 'TASK_REJECTED',
    TASK_STARTED: 'TASK_STARTED',
    TASK_COMPLETED: 'TASK_COMPLETED'
};

module.exports = {
    ROLES,
    TASK_STATUS,
    STATUS_TRANSITIONS,
    isValidTransition,
    NOTIFICATION_TYPES
};
